# muxplex theme: catppuccin-mocha
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left "#[bg=#cba6f7,fg=#1e1e2e,bold] #S #[bg=#1e1e2e] "
set -g status-right "#[bg=#313244,fg=#cdd6f4] #{pane_current_path} #[bg=#b4befe,fg=#1e1e2e,bold] #H %b %d %H:%M "
set -g status-left-length 30
set -g status-right-length 120
set -g window-status-format "#[bg=#313244,fg=#cdd6f4] #I:#W "
set -g window-status-current-format "#[bg=#b4befe,fg=#1e1e2e,bold] #I:#W "
set -g window-status-separator ""
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#b4befe"
set -g message-style "bg=#313244,fg=#cdd6f4"
